# -*- coding: utf-8 -*-
"""Agente_RAG DE FVH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7kwGHlJ27SiJx9UWOjQGaPFV7Fo5k4K

# Agente-FVH.ipynb

Agente experto en Forraje Verde Hidropónico (FVH) con triaje + RAG + LangGraph.

Flujo: `triaje` clasifica la pregunta en `RESPONDER` (usa el RAG sobre el manual FAO), `FUERA_TEMA` (responde "no lo sé") o `ASESOR` (deriva a un humano con un mensaje fijo).

## Instalación de dependencias
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q -U langchain
# %pip install -q -U langgraph
# %pip install -q -U langchain-openai
# %pip install -q -U langchain-community
# %pip install -q -U langchain-classic
# %pip install -q -U langchain_text_splitters
# %pip install -q -U faiss-cpu
# %pip install -q -U pymupdf

"""## Conexión al LLM

Guarda tu API key de OpenAI en el gestor de secretos de Colab (ícono de llave) con el nombre `OPENAI_API_KEY`.
"""

import os
from google.colab import userdata

api_key = userdata.get("Cesar")
os.environ["OPENAI_API_KEY"] = api_key

from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-4.1-mini", temperature=0)

respuesta = llm.invoke("¿Qué es el Forraje Verde Hidropónico?")
respuesta.content

"""## Prompt de triaje

Este nodo clasifica cada pregunta en 3 rutas antes de tocar el RAG.
"""

PROMPT_TRIAJE = """
Eres el clasificador de un asistente que es experto ÚNICAMENTE en Forraje Verde
Hidropónico (FVH), basado en el Manual Técnico de la FAO.

Dado el mensaje del usuario, devuelve SOLO un JSON con:
{
  "decision": "RESPONDER" | "FUERA_TEMA" | "ASESOR"
}

Reglas:
- "RESPONDER": la pregunta trata sobre producción, ventajas, semillas, instalaciones,
  condiciones ambientales, fertilización, alimentación animal, costos, factores de
  rendimiento, o cualquier otro aspecto del Forraje Verde Hidropónico.
- "FUERA_TEMA": la pregunta NO tiene relación con FVH (otro tema, cultura general,
  charla casual, etc.).
- "ASESOR": el usuario pide explícitamente hablar con una persona, un experto humano,
  un asesor, soporte humano, o dice que quiere hablar "con alguien" en vez del bot.

Ante la duda entre RESPONDER y FUERA_TEMA, prioriza FUERA_TEMA.
"""

from typing import Literal, Dict
from pydantic import BaseModel

class TriajeOut(BaseModel):
    decision: Literal["RESPONDER", "FUERA_TEMA", "ASESOR"]

from langchain_core.messages import SystemMessage, HumanMessage

chain_de_triaje = llm.with_structured_output(TriajeOut)

def triaje(mensaje: str) -> Dict:
    salida: TriajeOut = chain_de_triaje.invoke(
        [
            SystemMessage(content=PROMPT_TRIAJE),
            HumanMessage(content=mensaje)
        ]
    )
    return salida.model_dump()

mensajes_de_prueba = [
    "¿Qué es el Forraje Verde Hidropónico?",
    "¿Cuánto tiempo tarda la producción?",
    "¿Quién ganó el mundial de fútbol?",
    "Quiero hablar con un asesor",
]

for pregunta in mensajes_de_prueba:
    r = triaje(pregunta)
    print(f"{pregunta} -> {r}")

"""## Base documental (RAG)

Sube tus PDFs del manual FAO (segmentados por tema) a la carpeta `/content/knowledge_base/` en Colab antes de correr esta celda.
"""

from pathlib import Path
from langchain_community.document_loaders import PyMuPDFLoader

docs = []
carpeta = Path("/content/")

for n in carpeta.glob("*.pdf"):
    try:
        loader = PyMuPDFLoader(str(n))
        cargados = loader.load()
        for d in cargados:
            d.metadata["source_file"] = n.name
        docs.extend(cargados)
        print(f"Archivo cargado: {n.name}")
    except Exception as e:
        print(f"Error cargando archivo: {n.name} - {e}")

print(f"Total de documentos cargados: {len(docs)}")

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=120)
chunks = splitter.split_documents(docs)

print(f"Total de fragmentos: {len(chunks)}")

from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS

modelo_embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

vectorstore = FAISS.from_documents(chunks, modelo_embeddings)

retriever = vectorstore.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={"score_threshold": 0.3, "k": 4}
)

"""## Cadena RAG"""

from langchain_core.prompts import ChatPromptTemplate
from langchain_classic.chains.combine_documents import create_stuff_documents_chain

prompt_rag = ChatPromptTemplate([
    ("system",
     """
     Eres un asistente técnico experto en Forraje Verde Hidropónico (FVH),
     basado en el Manual Técnico de la FAO.
     Responde siempre utilizando el contexto que te paso.
     Si no hay información sobre la pregunta en el contexto, responde solo 'No lo sé'.
     """),
    ("human", "Contexto: {context} \n Pregunta del usuario: {input}")
])

document_chain = create_stuff_documents_chain(llm, prompt_rag)

from typing import Dict

def busqueda_de_respuestas_RAG(pregunta) -> Dict:
    documentos_relacionados = retriever.invoke(pregunta)

    if not documentos_relacionados:
        return {
            "respuesta": "No lo sé",
            "fuentes": [],
            "documentos_encontrados": False
        }

    answer = document_chain.invoke({
        "input": pregunta,
        "context": documentos_relacionados
    })

    if answer.rstrip(".!?") == "No lo sé":
        return {
            "respuesta": "No lo sé",
            "fuentes": [],
            "documentos_encontrados": False
        }

    fuentes = sorted({d.metadata.get("source_file", "?") for d in documentos_relacionados})
    return {
        "respuesta": answer,
        "fuentes": fuentes,
        "documentos_encontrados": True
    }

r = busqueda_de_respuestas_RAG("¿Qué semillas pueden utilizarse para producir FVH?")
print(r)

"""## Agente con LangGraph

Une el triaje y el RAG en un grafo con 3 rutas: `responder`, `fuera_tema`, `asesor`.
"""

from typing import TypedDict, List

class AgentState(TypedDict, total=False):
    pregunta: str
    triaje: dict
    respuesta: str
    fuentes: List[str]
    accion_final: str

MENSAJE_FUERA_TEMA = (
    "No lo sé. Solo soy un asistente experto en Forraje Verde Hidropónico (FVH), "
    "así que no puedo ayudarte con ese tema."
)

MENSAJE_ASESOR = (
    "Voy a comunicarte con un asesor humano para que te ayude con esto. "
    "En breve alguien del equipo se pondrá en contacto contigo."
)

def nodo_triaje(state: AgentState) -> AgentState:
    print("Ejecutando nodo triaje...")
    return {"triaje": triaje(state["pregunta"])}

def nodo_responder(state: AgentState) -> AgentState:
    print("Ejecutando nodo responder (RAG)...")
    respuesta_RAG = busqueda_de_respuestas_RAG(state["pregunta"])

    if not respuesta_RAG["documentos_encontrados"]:
        return {
            "respuesta": MENSAJE_FUERA_TEMA,
            "fuentes": [],
            "accion_final": "FUERA_TEMA"
        }

    return {
        "respuesta": respuesta_RAG["respuesta"],
        "fuentes": respuesta_RAG["fuentes"],
        "accion_final": "RESPONDER"
    }

def nodo_fuera_tema(state: AgentState) -> AgentState:
    print("Ejecutando nodo fuera_tema...")
    return {
        "respuesta": MENSAJE_FUERA_TEMA,
        "fuentes": [],
        "accion_final": "FUERA_TEMA"
    }

def nodo_asesor(state: AgentState) -> AgentState:
    print("Ejecutando nodo asesor...")
    return {
        "respuesta": MENSAJE_ASESOR,
        "fuentes": [],
        "accion_final": "ASESOR"
    }

def arista_decision_triaje(state: AgentState) -> str:
    print("Decidiendo el flujo despues del nodo triaje...")
    decision = state["triaje"]["decision"]
    if decision == "RESPONDER":
        return "responder"
    elif decision == "ASESOR":
        return "asesor"
    else:
        return "fuera_tema"

from langgraph.graph import START, END, StateGraph

workflow = StateGraph(AgentState)

workflow.add_node("triaje", nodo_triaje)
workflow.add_node("responder", nodo_responder)
workflow.add_node("fuera_tema", nodo_fuera_tema)
workflow.add_node("asesor", nodo_asesor)

workflow.add_edge(START, "triaje")
workflow.add_conditional_edges("triaje", arista_decision_triaje, {
    "responder": "responder",
    "fuera_tema": "fuera_tema",
    "asesor": "asesor"
})
workflow.add_edge("responder", END)
workflow.add_edge("fuera_tema", END)
workflow.add_edge("asesor", END)

grafo = workflow.compile()

"""## Visualizar el grafo"""

from IPython.display import display, Image

graph_bytes = grafo.get_graph().draw_mermaid_png()
display(Image(graph_bytes))

"""## Probar el agente"""

PREGUNTA = "¿Cuáles son las ventajas del FVH frente al forraje tradicional?"

respuesta = grafo.invoke({"pregunta": PREGUNTA})
print("")
print(f"PREGUNTA: {PREGUNTA}")
print(f"DECISIÓN: {respuesta['triaje']['decision']}")
print(f"ACCIÓN FINAL: {respuesta['accion_final']}")
print(f"RESPUESTA: {respuesta['respuesta']}")
if respuesta.get("fuentes"):
    print(f"FUENTES: {respuesta['fuentes']}")

mensajes_de_prueba = [
    "¿Qué es el Forraje Verde Hidropónico?",
    "¿Cuánto tiempo tarda la producción?",
    "¿Cuál es el costo aproximado de producción?",
    "¿Quién ganó el mundial de fútbol?",
    "Quiero hablar con un asesor",
]

for pregunta in mensajes_de_prueba:
    respuesta = grafo.invoke({"pregunta": pregunta})
    print("")
    print(f"PREGUNTA: {pregunta}")
    print(f"DECISIÓN: {respuesta['triaje']['decision']} | ACCIÓN FINAL: {respuesta['accion_final']}")
    print(f"RESPUESTA: {respuesta['respuesta']}")
    if respuesta.get("fuentes"):
        print(f"FUENTES: {respuesta['fuentes']}")
    print("-------------------------------------------------------------")